[tool.poetry]
name = "secret-santa"
version = "0.1.0"
description = ""
authors = ["Sean Behan <codebam@riseup.net>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
